// <auto-generated />
namespace HandIn2._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TryFixedHouseNr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TryFixedHouseNr));
        
        string IMigrationMetadata.Id
        {
            get { return "201710012022326_TryFixedHouseNr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
